name: API Key Secret

## Store the API Key to the ACS database

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

on:
  push:
    branches: [ main ]

env:
  API_KEY: ${{ secrets.API_KEY }}
    
  #run: |
    
